class TestConstant
  #TODO: FIGURE HOW TO GET THIS!
  # XBOX Forgotten  Heros"
  VALID_XBOX_GROUP_ID = 654264
  #TODO: FIGURE HOW TO GET THIS!
  # PLAYSTATION Cool kids table
  VALID_PLAYSTATION_GROUP_ID = 224949

  VALID_XBOX_GAMERTAG = "tj71587"
  VALID_XBOX_GAMERTAG_CHARACTER_NUMBER = 3
  VALID_PLAYSTATION_GAMERTAG = "triplewreck"
  VALID_PLAYSTATION_GAMERTAG_CHARACTER_NUMBER = 3

  VALID_XBOX_GAMERTAG_WITH_SPACES = "LL TIGER LL"

  VALID_XBOX_MEMBERSHIP_TYPE_ID = 1
  VALID_PLAYSTATION_MEMBERSHIP_TYPE_ID = 2

  INVALID_XBOX_GAMERTAG = "tj717171717171771717"
  INVALID_PLAYSTATION_GAMERTAG = "tj717171717171771717"
  INVALID_MEMBERSHIP_ID = "11111111111111111111111111111111"
  INVALID_MEMBERSHIP_ID_ERROR_CODE = 7
  INVALID_MEMBERSHIP_TYPE_ID = 99
  INVALID_GAMERTAG_ERROR_CODE = 1
  INVALID_MEMBERSHIP_TYPE_ERROR_CODE = 7

  VALID_AGGREGATE_STATS_ERROR_CODE = 1

  VALID_CLASS_TYPE_TITAN_ID = 0
  VALID_CLASS_TYPE_HUNTER_ID = 1
  VALID_CLASS_TYPE_WARLOCK_ID = 2
  INVALID_CLASS_TYPE_ID = 99
end